refactor: auth token로직 분리, Provider 생성
wildflower-keeper/mobile pull request #60
Opened 2024-11-10 14:59 UTC by eomsteve

## What is this PR🔍?

- [x] 새로운 기능 추가
- [x] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [x] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [x] 파일 혹은 폴더명 수정
- [x] 파일 혹은 폴더 삭제

## - ISSUE 

## Changes📃

- authProvider로 클라이언트 토큰 데이터 관리
- authTokenStore로 안드로이드 keyChain 데이터 관리
- userProvider로 유저 데이터 관리
- 최상단에서 Provider로 로그인, 회원가입 이전부터 토큰 접근
- 로그인(회원가입) 이후로는 토큰 저장되므로 유저 데이터로 관리
- api 호출시 토큰은 fetch 리팩토링 시 반영
- 필요없는 파일 제거

## Screenshot📸

|기능|스크린샷|
|---|---|
|||

2024-11-11 05:47 UTC, hokidoki requested changes
p1 : request 인터셉터를 활용해서, 토큰을 헤더에 셋 할 수 있도록 수정해주세요. 모든 API 호출자마다 이러는건 낭비인듯 합니다.

2024-11-15 12:10 UTC, reeny404 commented on src/utils/api/auth.ts
> +const {token} = useAuthStore();
요기에서 에러 나는데 요거 테스트해보셨나요?
![image](https://github.com/user-attachments/assets/a4f34f1c-62e6-4f35-a165-b4cb6e2921f4)

2024-11-15 12:46 UTC, eomsteve reviewed
테스트를 Fetch 이후에 할까해서 오류가 생기면 그때 대응하려 했습니다. 

테스트 자체는 못했어요!

2024-11-15 13:11 UTC, reeny404 commented on src/utils/api/auth.ts
> +const {token} = useAuthStore();
요거 에러나서 요렇게 넣어두었습니다.
![image](https://github.com/user-attachments/assets/7fa602b8-af58-45da-9448-865b9a1433a2)

2024-11-16 14:36 UTC, closed without merging