Feat/spt 22/app fetch
wildflower-keeper/mobile pull request #61
Opened 2024-11-11 16:16 UTC by reeny404

## What is this PR🔍?
- [x] 코드 리팩토링
- [x] 주석 추가 및 수정

## - ISSUE 
https://met8711.atlassian.net/browse/SPT-22

## Changes📃

## Screenshot📸

|기능|스크린샷|
|---|---|
|||

2024-11-12 02:51 UTC, eomsteve requested changes
제가한 브랜치에서 작업한게 아닌거 같아요! 이부분은 제가 다시 설명드리겠습니당

혹시 오늘 시간이 언제 되실까요!

2024-11-16 12:03 UTC, eomsteve requested changes
그리고 몇몇 파일에서 import하고 있지만 사용하지 않는 코드도 삭제 해주시면 좋을 것 같아요!

2024-11-16 12:03 UTC, eomsteve commented on src/hooks/queries/useLocation.tsx
>          {
이쪽 fetch도 업데이트된 패치로 바꿔서 구현 해 주세요

2024-11-16 12:03 UTC, eomsteve commented on src/screens/AuthSignup.screen.tsx
>        if (result.errorCode) {
여기 위에도 바뀐 fetch로 업데이트 해야할것 같습니다

2024-11-16 13:38 UTC, reeny404 commented on src/utils/api/api.ts
> +const hasAuthToken = (header: HeadersInit | undefined): boolean => {
뭔가 commit 한 게 빠진 것 같네요. 다시 수정해서 올리겠습니다.

2024-11-16 13:38 UTC, reeny404 commented on src/hooks/queries/useLocation.tsx
>          {
수정 완료

2024-11-16 13:45 UTC, reeny404 commented on src/screens/AuthSignup.screen.tsx
>        if (result.errorCode) {
수정 완료

2024-11-16 14:23 UTC, eomsteve approved these changes
LGTM

2024-11-16 14:25 UTC, merged